### ISSUE TITLE
Error: could not find function "shell.exec"

### ISSUE THREAD

**Issue by Patrikios** [gimoya/theBioBucket-Archives#6]
The initial stage (# get txt-file name and open it ) gives me an error:

Error: could not find function "shell.exec"

Any idea?
BTW, also function shell() for text mining seems to be restricted under Linux.

**Comment by gimoya** [comment]
I'm guessing that you refer to https://github.com/gimoya/theBioBucket-Archives/blob/master/R/txtmining_pdf.R#l16 ...

`shell.exec` as well as `shell()` and `system()` are Win-only, as you can take from the docs!

See also this: http://stackoverflow.com/questions/12273346/system-independent-method-of-opening-afile
